---

- name: Assign backup date & time
  hosts: localhost
  tasks:
    - name: Retrieve localhost date & time
      debug:
        var: ansible_date_time

- name: Backup web host data
  hosts: "{{ webhost_ssh_host }}"
  vars:
    webhost: "{{ webhost_co }}_{{ webhost_ssh_host}}"
    datetime: "{{ ansible_date_time.iso8601_basic_short }}{{ ansible_date_time.tz }}"
  tasks:
  - name: Create backup directory
    file:
      path: "~/backup-{{ datetime }}"
      state: directory
  - name: Backup web host Wordpress MySQL DB
    shell: "mysqldump --databases {{ webhost_db_target }} --user {{ webhost_db_user}} --password='{{ webhost_db_passwd }}' > {{ webhost }}_mysqldump_{{ webhost_db_target }}-{{ datetime }}.sql"
    args: 
      chdir: "~/backup-{{ datetime }}"
  - name: Archive home directory, excluding target archive file
    shell: "tar --exclude={{ webhost }}_backup_{{ datetime }}.tar.gz -czpsf {{ webhost}}_backup_{{ datetime }}.tar.gz --transform 's,^,{{ webhost }}_backup_{{ datetime }}/,' -C ~ ."
    args:
      chdir: "~/backup-{{ datetime }}"
  - name: Fetch backup archive
    fetch:
      src: "~/backup-{{ datetime }}/{{ webhost }}_backup_{{ datetime }}.tar.gz"
      dest: "{{ backup_dst_dir }}"
      flat: yes
  - name: Remove backup directory and files
    file:
      path: "~/backup-{{ datetime }}"
      state: absent
